version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat-app
      - PORT=5000
    networks:
      - app-network

  front:
    build: ./public
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
