version: '3.8'
services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network

  front:
    build: ./public
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
