name: Backend CI/CD

on:
  workflow_call:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/chat-app-backend:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./server
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export TAG=${{ github.ref_name }}
            export REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            export CLIENT_URL=${{ secrets.CLIENT_URL }}
            export MONGODB_URI=mongodb://chat-app-real-time-mongodb-1:27017/chat-app

            # Tạo mạng Docker nếu chưa tồn tại
            sudo docker network create chat-app-real-time_app-network || true
            
            sudo docker pull ${{ env.IMAGE_NAME }}
            
            # Khởi động lại container mới
            sudo docker stop ${{ secrets.BACKEND_CONTAINER_NAME }} || true
            sudo docker rm ${{ secrets.BACKEND_CONTAINER_NAME }} || true
            sudo docker run -d --name ${{ secrets.BACKEND_CONTAINER_NAME }} \
              --network chat-app-real-time_app-network \
              -p ${{ secrets.BACKEND_PORT }}:5000 \
              -e PORT=5000 \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              ${{ env.IMAGE_NAME }}
