name: Backend CI/CD

on:
  workflow_call:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/chat-app-backend:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./server
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Xóa file docker.list cũ nếu tồn tại
            sudo rm -f /etc/apt/sources.list.d/docker.list

            # Cài đặt Docker nếu chưa có
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              
              # Cập nhật package list
              sudo apt-get update
              
              # Cài đặt các packages cần thiết
              sudo apt-get install -y \
                  ca-certificates \
                  curl \
                  gnupg

              # Tạo thư mục cho GPG key
              sudo install -m 0755 -d /etc/apt/keyrings
              
              # Tải và thêm Docker's GPG key
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              sudo chmod a+r /etc/apt/keyrings/docker.gpg

              # Thêm repository
              echo \
                "deb [arch="\$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                "\$(. /etc/os-release && echo "\$VERSION_CODENAME")" stable" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

              # Cập nhật package list
              sudo apt-get update

              # Cài đặt Docker
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

              # Thêm user hiện tại vào nhóm docker
              sudo usermod -aG docker \$USER
            else
              echo "Docker already installed"
            fi

            # Kiểm tra Docker đã cài đặt thành công
            docker --version
            docker compose version

            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export TAG=${{ github.ref_name }}
            export REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            export CLIENT_URL=${{ secrets.CLIENT_URL }}
            
            sudo docker pull ${{ env.IMAGE_NAME }}
            
            # Khởi động lại toàn bộ stack
            cd $DOCKER_COMPOSE_DIR
            sudo docker-compose -f docker-compose.prod.yml down
            sudo docker-compose -f docker-compose.prod.yml up -d
