name: Frontend CI/CD

on:
  workflow_call:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/chat-app-frontend:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./public
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl start docker
            sudo docker pull ${{ env.IMAGE_NAME }}
            sudo docker stop ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
            sudo docker rm ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
            sudo docker run -d \
              --name ${{ secrets.FRONTEND_CONTAINER_NAME }} \
              -p 3000:3000 \
              ${{ env.IMAGE_NAME }}
