name: Frontend CI/CD

on:
  workflow_call:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/chat-app-frontend:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./public
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker network create chat-app-real-time_app-network || true
            sudo docker pull ${{ env.IMAGE_NAME }}
            sudo docker stop ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
            sudo docker rm ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
            sudo docker run -d \
              --name ${{ secrets.FRONTEND_CONTAINER_NAME }} \
              --network chat-app-real-time_app-network \
              -p 3000:3000 \
              -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
              -e REACT_APP_LOCALHOST_KEY=chat-app-current-user \
              -e REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }} \
              -e REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }} \
              -e REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }} \
              -e REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }} \
              -e REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }} \
              -e REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }} \
              -e REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }} \
              ${{ env.IMAGE_NAME }}
