name: CI/CD Pipeline

on:
  push:
    tags:
      - '*'

jobs:
  setup-infra:
    uses: ./.github/workflows/setup-infra.yml
    secrets: inherit

  frontend:
    needs: setup-infra
    uses: ./.github/workflows/frontend.yml
    secrets: inherit

  backend:
    needs: setup-infra
    uses: ./.github/workflows/backend.yml
    secrets: inherit