name: Setup Infrastructure

on:
  workflow_dispatch:  # Cho phép chạy thủ công khi cần
  workflow_call:      # Cho phép được gọi từ workflow khác

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: \${{ secrets.EC2_HOST }}
          username: \${{ secrets.EC2_USER }}
          key: \${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > install-docker.sh << 'EOL'
            #!/bin/bash
            
            # Định nghĩa file marker
            DOCKER_MARKER="/usr/local/etc/.docker-installed"
            
            # Function kiểm tra Docker
            check_docker() {
                if command -v docker &> /dev/null && command -v docker compose &> /dev/null; then
                    return 0
                else
                    return 1
                fi
            }
            
            # Kiểm tra marker file và Docker
            if [ -f "\$DOCKER_MARKER" ] && check_docker; then
                echo "Docker đã được cài đặt trước đó."
                echo "Docker version:"
                docker --version
                echo "Docker Compose version:"
                docker compose version
                exit 0
            fi
            
            echo "Starting installation docker..."
            
            sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo "\$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            
            if check_docker; then
                echo "Docker cài đặt thành công!"
                sudo docker --version
                docker compose version
                sudo systemctl enable docker
                sudo systemctl status docker
                sudo mkdir -p /usr/local/etc
                echo "Docker installed on \$(date)" | sudo tee \$DOCKER_MARKER
            else
                echo "Cài đặt Docker thất bại!"
                exit 1
            fi
            EOL
            
            chmod +x install-docker.sh
            ./install-docker.sh